# Generated by Django 2.2.17 on 2021-03-31 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 14, 18, 37, 155830, tzinfo=utc)),
        ),
    ]
