# Generated by Django 2.2.17 on 2021-03-31 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0002_auto_20210331_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 14, 21, 37, 332255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
