# Generated by Django 2.2.17 on 2021-04-01 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0003_auto_20210401_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 18, 59, 48, 768471, tzinfo=utc)),
        ),
    ]
