# Generated by Django 2.2.17 on 2021-03-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0004_auto_20210325_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
    ]
