# Generated by Django 2.2.17 on 2021-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0005_remove_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.DateTimeField(null=True),
        ),
    ]
