# Generated by Django 2.2.17 on 2021-04-02 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0006_auto_20210401_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saved_films',
            field=models.ManyToManyField(blank=True, to='filmfanatics.Film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 7, 3, 273474, tzinfo=utc)),
        ),
    ]
