# Generated by Django 2.2.17 on 2021-03-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0006_auto_20210325_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.DateField(null=True),
        ),
    ]
