# Generated by Django 2.2.17 on 2021-03-29 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0007_auto_20210325_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='posted_at',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
