# Generated by Django 2.2.17 on 2021-04-02 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0007_auto_20210402_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saved_films',
            field=models.ManyToManyField(blank=True, null=True, to='filmfanatics.Film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 59, 11, 496119, tzinfo=utc)),
        ),
    ]
