# Generated by Django 2.2.17 on 2021-03-29 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0008_auto_20210329_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 18, 19, 0, 471140)),
        ),
    ]
