# Generated by Django 2.2.17 on 2021-03-29 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0009_auto_20210329_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 18, 32, 46, 860079, tzinfo=utc)),
        ),
    ]
