# Generated by Django 2.2.17 on 2021-03-30 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0010_auto_20210329_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 16, 34, 2, 350914, tzinfo=utc)),
        ),
    ]
