# Generated by Django 2.2.17 on 2021-03-30 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmfanatics', '0012_auto_20210330_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reset_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 18, 34, 39, 546766, tzinfo=utc)),
        ),
    ]
